config/routes.rb
Rails.application.routes.draw do
  resources :surveys

  resources :resources

end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:name, :category)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:danger, :injured, :place_to_sleep, :next_meal, :employed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RenoResources</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.category %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @resource.category %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Are you in danger?" %><br>
    Yes <%= f.radio_button :danger, "0" %>
      <div>
        <input type="checkbox" class="resourceCheck"><br>
        <input type="checkbox" class="resourceCheck"><br>
        <input type="checkbox" class="resourceCheck"><br>
        <input type="checkbox" class="resourceCheck"><br>
      </div>
    No <%= f.radio_button :danger, "1" %>
  </div>
  <div class="field">
    <%= f.label "Are you injured?" %><br>
    Yes <%= f.radio_button :injured, "0" %>
    No <%= f.radio_button :injured, "1" %>
  </div>
  <div class="field">
    <%= f.label "Do you have a safe place to sleep?" %><br>
    Yes <%= f.radio_button :place_to_sleep, "0" %>
    No <%= f.radio_button :place_to_sleep, "1" %>
  </div>
  <div class="field">
    <%= f.label "Do you know where your next meal will come from?" %><br>
    Yes <%= f.radio_button :next_meal, "0" %>
    No <%= f.radio_button :next_meal, "1" %>
  </div>
  <div class="field">
    <%= f.label "Are you currently employed?" %><br>
    Yes <%= f.radio_button :employed, "0" %>
    No <%= f.radio_button :employed, "1" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit"%>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<table>
  <thead>
    <tr>
      <th>Danger</th>
      <th>Injured</th>
      <th>Place to sleep</th>
      <th>Next meal</th>
      <th>Employed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.danger %></td>
        <td><%= survey.injured %></td>
        <td><%= survey.place_to_sleep %></td>
        <td><%= survey.next_meal %></td>
        <td><%= survey.employed %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Danger:</strong>
  <%= @survey.danger %>
</p>

<p>
  <strong>Injured:</strong>
  <%= @survey.injured %>
</p>

<p>
  <strong>Place to sleep:</strong>
  <%= @survey.place_to_sleep %>
</p>

<p>
  <strong>Next meal:</strong>
  <%= @survey.next_meal %>
</p>

<p>
  <strong>Employed:</strong>
  <%= @survey.employed %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>